### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by jbeguna04** [irelandscape/quearn#1]
Hello @irelandscape , I would like to propose a logo for your great project. I am a graphics designer and would like to help you regarding this issue. Thank you!

**Comment by irelandscape** [comment]
Great, thanks @jbeguna04!

Here is a transcript from Discord:

> Ideally, I'd be looking for a logo in vectorial format (SVG)
With simple but strong shapes.
The logo could be complemented with the text "StemQA" beside where there is horizontal space.
A single tone version would be great as well and it should look good in white or black color.
The logo would be credited to the designer on the StemQA UI.

Thanks a million!

**Comment by irelandscape** [comment]
Hi @jbeguna04,

I had a look at your past logo designs and here are those which styles would fit best StemQA I think:

* https://steemit.com/utopian-io/@jbeguna04/3-design-logo-proposal-for-comprendre-steem
* https://steemit.com/utopian-io/@jbeguna04/logo-design-jpass
* https://steemit.com/utopian-io/@jbeguna04/steeditor-logo-proposal
* https://steemit.com/utopian-io/@jbeguna04/openscale-logo-proposal-accepted-and-used (I like the simple strong shapes in this one)

Something more abstract like the Utopian logo is great as well.

Anyway, I leave the rest to your imagination now!

**Comment by jbeguna04** [comment]
Ill be presenting some designs of the logo for you to see. Thank you
